data:
  root_dir: '/home/pover/Datasets/barcode'
  batch_size: 8
  input_size: [ 640, 1024 ]

model:
  in_channels: 1
  n_classes: 3
  inc_channels: 32
  interpolation: 'nearest'
  gamma: 2.0
  alpha: 0.5
  init_lr: 5e-4

trainer:
  accelerator: 'auto'
  strategy: 'auto'
  devices: 'auto'
  precision: '32-true'
  max_epochs: 500
  sync_batchnorm: True
  check_val_every_n_epoch: 2
